window.SPR=function(){function C(a,d){var c=this;c.N=[];c.H=a||{};c.ud=b.Yc;c.ta=!1;c.Qc=d||b.zc;r.uc(c.Qc);l.b(a[b.ua]);a[b.f]=a[b.f]||u.current[b.f];a[b.url]=a[b.url]||k.ma();a[b.title]||(a[b.title]=k.la(a[b.url]));if(a[b.url])c.b=function(){if(c.Mc())return c.qc(),c;l[b.error](c.Vb());return null},c[b.ad]=function(e){c.Nc(e)?c.rc(e):c.Rb(e);return c},c[b.Tc]=function(e){c.Kc(e)?c.pc(e):c.Qb();return c},c[b.fd]=function(e){c.Oc(e)?c.sc(e):c.Sb();return c},c[b.Rc]=function(){c.ta||(c.w(c.ha(c.ha())),
c[b.Ka](100),c.ta=!0);return c},c[b.Ka]=function(e){if(g.contains(c.N,e))return null;if(g.contains(g.Z,e)){var f=c.l();f[b.o]=b.La;f[b.La]=c.yb(e);c.w(f)}else l[b.error](b.Fb);return c},c.yb=function(e){var f,h=g.Z,p={};if(!g.contains(h,e))l[b.error](b.wa);else if(!g.contains(c.N,e))for(f=0;f<h.length;f+=1){var m=h[f];e>=m&&!g.contains(c.N,m)&&(c.N.push(m),p[m]=!0,l[b.info](b.Ea+m))}return p},c.w=function(e){r.i(b.m,b.Vc,e)},c.qc=function(){c.w(c.Db())},c.xd=function(){return u.current},c.l=function(){return z.ea(c.H)},
c.Db=function(){var e=c.l();e[b.o]=b.Xc;return e},c.Mc=function(){var e;for(e=0;e<v.length;e+=1)if(!c.H[v[e]])return!1;return!0},c.Vb=function(){var e,f=[];for(e=0;e<v.length;e+=1)c.H[v[e]]||f.push(v[e]);return b.Hb+f.join(", ")},c.rc=function(e){c.w(c.Cc(e))},c.Nc=function(e){return e===b.dd||e===b.ed},c.Cc=function(e){var f=c.l();f[b.o]=b.bd;f[b.cd]=e;return f},c.Rb=function(e){if(e)l[b.error](e+b.Ib);else l[b.error](b.Ic)},c.ha=function(){var e=c.l();e[b.o]=b.Sc;return e},c.pc=function(e){c.w(c.tb(e))},
c.tb=function(e){var f=c.l();f[b.o]=b.Uc;f[b.Zc]=e;return f},c.Kc=function(e){return!isNaN(e)},c.Qb=function(){l[b.error](b.Eb)},c.sc=function(e){c.w(c.Dc(e))},c.Dc=function(e){var f=c.l();f[b.o]=b.gd;f[b.$c]=e;return f},c.Oc=function(e){return!isNaN(e)&&c.Pc(e)},c.Pc=function(e){return g.gb(g.hd,e)},c.Sb=function(){l[b.error](b.Gb)};else l[b.error](b.ba+b.na)}var b={m:"edge.simplereach.com",version:"2.18.8",eb:"d8rk54i4mohrb.cloudfront.net",global:"SPR",gc:"__reach_config",oc:"__memo_config",
Cb:"/n",Ec:"/t",Vc:"/v",oa:"/event",ab:"/pixel?bad=true&error=",rd:"/iframe.html",fb:"/container.html",Ga:"000000000000000000000000",ba:"SPR-ERROR: ",na:"100 - Missing url",bb:"cache_buster",Ca:"__srret",Ja:"__srui",R:"0",$b:"1",Bb:"img",ac:"1px",width:"width",g:"undefined",error:"error",Wb:"off",info:"info",K:"SPR_DEBUG",Fa:"//",ca:"string",referrer:"referrer",uid:"uid",S:"callback",i:"jsonp",url:"url",title:"title",f:"pid",va:"ignore_metadata",Ub:"meta",time:"time",lb:"datetime",c:"property",
Lb:"itemprop",name:"name",cb:"canonical",link:"link",rel:"rel",jd:"article",Yb:"og:url",Hc:"twitter:url",Xb:"og:title",Gc:"twitter:title",Ua:"article:published_at",Ya:"article:sr_published_at",Va:"article:published_time",kb:"datePublished",bc:"og:pubdate",Ba:"pubdate",Sa:"article:author",Wa:"article:sr_author",da:"author",$a:"article:tag",Za:"article:sr_tag",Ta:"article:section",Xa:"article:sr_section",content:"content",href:"href",Da:"s",r:"r",t:"t",e:"e",x:"x",n:"n",Jc:"v",ua:"ignore_errors",fc:"preview",
B:"authors",C:"channels",L:"tags",h:"date",td:"inframe",Pa:"ajax",Ac:"social_tracking",pd:"iframe",ib:"custom_tracking",hc:"reach_tracking",v:"ref_url",Y:"page_url",Cd:"user_id",Tb:"manual_scroll_depth",ja:"content_height",wd:"rd",od:"fb",kd:"de",cc:"pi",hb:"csd",dc:"partners-api.pinterest.com",ec:"/v1/urls/count.json",wa:"[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100",Ea:"[info] sending scrollDepth of: ",nc:"[info] scroll depth not activated, not sending data",zc:"SimplereachVideo",
o:"event_name",Hb:"Missing params please provide a ",Ib:" is not a valid start event type.",Ic:"Cannot have an undefined start type. Please provide a start type.",Eb:"Please pass a valid number",Fb:"[error] Invalid quartile please send quartiles of only: 25, 50, 75 or 100",yd:"[error] Quartile for this video already sent",Gb:"Please pass a valid threshold number",Wc:"video_id",Pb:"length",description:"description",Bd:"thumbnail_url",zd:"source_url",za:"networks",Yc:"video",ad:"start",Tc:"elapsed",
Rc:"complete",Ka:"quartile",fd:"elapsedThreshold",Xc:"init",bd:"start",Uc:"elapsed",La:"quartile",Sc:"complete",gd:"elapsed_threshold",cd:"start_type",dd:"auto",ed:"click",Zc:"seconds_elapsed",$c:"threshold"},g={lc:function(){return Math.random().toString(36).replace(/[^a-z]+/g,"")},jb:function(a){for(var d=[],c=/-|\//,e=[/\d{4}\/\d{1,2}\/\d{1,2}/,/\d{4}-\d{1,2}-\d{1,2}/,/20\d{6}/],f=0;f<e.length;f++){var h=a.match(e[f]);if(null!=h)return a=h[0],a.match(c)?d=a.split(c):(d[0]=a.substring(0,4),d[1]=
a.substring(4,6),d[2]=a.substring(6,8)),new Date(d[0],d[1]-1,d[2])}},s:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},log:function(a){window.console&&console.log(a)},Kb:function(a){return"[object String]"===Object.prototype.toString.call(a)},P:function(a){var d={},c;for(c in a)a.hasOwnProperty(c)&&(d[c]=a[c]);return d},ya:function(a,d){for(var c in d)d.hasOwnProperty(c)&&(a[c]=d[c]);return a},contains:function(a,d){return-1!==(a.join(",")+",").indexOf(d+
",")},gb:function(a,d){if(!isNaN(d)&&!this.Kb(d))for(var c=0;c<=a.length;c++)if(a[c]===d)return!0;return!1},V:function(a){typeof a===b.ca&&(a=a.split(","));if(this.s(a)){for(var d=0;d<a.length;d+=1)typeof a[d]===b.ca&&(a[d]=a[d].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}},G:function(){},qa:function(){return window.location.protocol+"//"},Z:[25,50,75,100],hd:[3,15,30,45]},w={encode:function(a,d){var c=[];if(g.s(a))for(var e=0,f;e<a.length;e+=1)f=a[e],/\[\]$/.test(d)?
c.push(encodeURIComponent(d)+"="+encodeURIComponent(f)):c.push(this.encode(f,d+"["+("object"===typeof f?e:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)c.push(encodeURIComponent(d)+"="+encodeURIComponent(a));else for(e in a)Object.prototype.hasOwnProperty.call(a,e)&&(d?c.push(this.encode(a[e],d+"["+e+"]")):c.push(this.encode(a[e],e)));return c.join("&")},decode:function(a){var d={},c=0,e={"true":!0,"false":!1,"null":null};for(a=a.replace(/\+/g," ").split("&");c<a.length;c+=1){var f=
a[c].split("="),h=decodeURIComponent(f[0]),p=d,m=0,n=h.split("]["),t=n.length-1;/\[/.test(n[0])&&/\]$/.test(n[t])?(n[t]=n[t].replace(/\]$/,""),n=n.shift().split("[").concat(n),t=n.length-1):t=0;if(2===f.length)if(f=(f=decodeURIComponent(f[1]))&&!isNaN(f)?+f:f===b.g?void 0:void 0!==e[f]?e[f]:f,t)for(;m<=t;m+=1)h=""===n[m]?p.length:n[m],p=p[h]=m<t?p[h]||(n[m+1]&&isNaN(n[m+1])?{}:[]):f;else g.s(d[h])?d[h].push(f):d[h]=void 0!==d[h]?[d[h],f]:f;else h&&(d[h]=void 0)}return d}},x={Aa:{},sa:function(a){var d=
document.cookie||"",c=this.Aa[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=new RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),this.Aa[a]=c);return(a=d.match(c))&&decodeURIComponent(a[1])},aa:function(a,d,c){var e="";c&&(e="; expires="+c.toGMTString());document.cookie=a+"="+d+e+"; path=/"},ld:function(a){this.aa(a,"",new Date(1982,5,13))}},u={current:{}},l={pa:!1,info:g.G,error:g.log,b:function(){window[b.K]&&(this.pa=!0,window[b.K][b.info]&&(this[b.info]=window[b.K][b.info]),window[b.K][b.error]&&
(this[b.error]=window[b.K][b.error]))},reset:function(){this.pa=!1;this[b.info]=g.G;this[b.info]=g.log},wc:function(a){var d=document.createElement(b.Bb);d.src=g.qa()+b.m+b.ab+a.message;d.setAttribute(b.width,b.ac);document.body?document.body.appendChild(d):document.head.appendChild(d)},xc:function(a){a===b.info?(this[b.info]=g.log,this[b.error]=g.log):a===b.error?(this[b.info]=g.G,this[b.error]=g.log):(this[b.info]=g.G,this[b.error]=g.G)}},k={R:0,F:{x:0,y:0},isVisible:!0,b:function(){function a(){e.isVisible=
document[f]?!1:!0}function d(){e.flush();window.removeEventListener("DOMContentLoaded",d,!1)}function c(){e.ready&&(document.detachEvent("onreadystatechange",c),p&&(p=!1,e.flush()))}var e=this;e.R=0;this.Zb(window,"mousemove",function(m){e.F={x:m.clientX,y:m.clientY}});if(typeof document.hidden!==b.g){var f="hidden";var h="visibilitychange"}else typeof document.mozHidden!==b.g?(f="mozHidden",h="mozvisibilitychange"):typeof document.msHidden!==b.g?(f="msHidden",h="msvisibilitychange"):typeof document.webkitHidden!==
b.g&&(f="webkitHidden",h="webkitvisibilitychange");typeof document.addEventListener!==b.g&&typeof f!==b.g&&document.addEventListener(h,a,!1);var p=!0;window.addEventListener?window.addEventListener("DOMContentLoaded",d,!1):document.attachEvent&&document.attachEvent("onreadystatechange",c)},Ma:function(a,d){var c=document.createElement("iframe"),e=document.body;c.setAttribute("name","spr");c.src=a;c.setAttribute("height","1");c.setAttribute("width","1");c.setAttribute("visible","false");c.setAttribute("id",
"spr-iframe-"+d);c.style.display="none";e||(e=this.j("BODY")[0]);e||(e=this.j("HEAD")[0]);l[b.info](a);e.appendChild(c);return c},pb:function(){return this.a(this,b.c,b.Yb)},nb:function(){return this.vb(this,b.cb)},qb:function(){return this.a(this,b.name,b.Hc)},rb:function(){return window.location.protocol+b.Fa+window.location.hostname+window.location.pathname},ma:function(){var a=this.nb()||this.pb()||this.qb()||this.rb();return g.s(a)?a[0]:a},ob:function(){var a=this.a(this,b.c,b.Ya)||this.a(this,
b.name,b.Ba)||this.a(this,b.c,b.Ba)||this.a(this,b.c,b.Ua)||this.a(this,b.c,b.Va)||this.a(this,b.c,b.bc)||this.wb(this,b.Lb,b.kb)||this.a(this,b.name,b.h);return g.s(a)?a[0]:a},mb:function(){return this.a(this,b.c,b.Wa)||this.a(this,b.c,b.Sa)||this.a(this,b.c,b.da)||this.a(this,b.name,b.da)},ka:function(a,d){return this.a(this,b.c,a)||this.a(this,b.c,d)},ra:function(){return document.referrer},la:function(a){a=this.a(this,b.c,b.Xb)||this.a(this,b.name,b.Gc)||document.title||a||!1;return g.s(a)?a[0]:
a},W:function(a,d,c,e,f){a=a.j(d);d=[];for(var h=0;h<a.length;h++)a[h].getAttribute(c)===e&&d.push(a[h].getAttribute(f));if(d.length)return 1==d.length?d[0]:d},vb:function(a,d){return this.W(a,b.link,b.rel,d,b.href)},a:function(a,d,c){return this.W(a,b.Ub,d,c,b.content)},wb:function(a,d,c){return this.W(a,b.time,d,c,b.lb)},ic:function(a){var d=document.body,c=this.j("BODY")[0],e=this.j("HEAD")[0];d&&d.contains(a)?d.removeChild(a):c&&c.contains(a)?c.removeChild(a):e&&e.contains(a)&&e.removeChild(a);
return a},Na:function(a){var d=this,c=document.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","spr");c.setAttribute("id","spr-script");c.src=a;l[b.info](a);this.X(function(){setTimeout(function(){d.j("HEAD")[0].appendChild(c)},1)});return c},u:[],ready:!1,flush:function(){var a=this.u.shift();for(this.ready=!0;a;)a(),a=this.u.shift()},X:function(a){function d(){/loaded|interactive|complete/.test(document.readyState)?c.flush():setTimeout(d,500)}var c=
this;this.ready?(this.u.push(a),this.flush()):document.documentElement.doScroll?window.self===window.top?function f(){if(!document.uniqueID&&document.expando)return this.u.push(a);try{document.documentElement.doScroll("left"),a()}catch(h){setTimeout(f,0)}}():(this.u.push(a),d()):(this.u.push(a),d())},Zb:function(a,d,c){a.addEventListener?a.addEventListener(d,c,!1):a.attachEvent("on"+d,c);return a},Wb:function(a,d,c){a.addEventListener?a.removeEventListener(d,c,!1):a.detachEvent("on"+d,c);return a},
O:function(){return(window.pageYOffset?window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.R},j:function(a){var d=[],c=0,e;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":d.push(document.getElementById(a.substring(1)));break;case ".":var f=document.getElementsByTagName("*");for(e=" "+a.substring(1)+" ";c<f.length;c+=1)a=(" "+f[c].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(e)&&d.push(f[c]);break;default:d=document.getElementsByTagName(a)}return d}},
z={ea:function(a){var d;var c=g.P(a);c[b.B]&&(c[b.B]=g.V(c[b.B]));c[b.C]&&(c[b.C]=g.V(c[b.C]));c[b.L]&&(c[b.L]=g.V(c[b.L]));c[b.h]&&typeof c[b.h]!==b.ca&&(c[b.h]=c[b.h].toString());c[b.referrer]=""==c[b.v]?"":this.$(c[b.referrer]);c[b.v]=this.$(c[b.v]);c[b.Y]=c[b.Y]||window.location.toString();c[b.uid]?c[b.uid]=c[b.uid]:(d=this.Ab())&&(c[b.uid]=d);c[b.url]&&(c[b.url]=this.mc(c[b.url]),a[b.url]=c[b.url]);return c},$:function(a){""!==a&&(a=a||k.ra());return a},Ab:function(){return x.sa(b.Ja)},mc:function(a){if(0===
a.indexOf("http%253A")||0===a.indexOf("https%253A"))a=decodeURIComponent(a);if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))a=decodeURIComponent(a);return a}},r={callbacks:{},T:b.global,uc:function(a){this.T=a},i:function(a,d,c,e,f){e=e||function(){};f||(f="cb");var h="cb"+g.lc(),p=this;c[f]=this.T+".API.callbacks."+h;f=g.qa();"file://"===f&&(f="http://");c[b.Jc]=b.version;c=w.encode(c);var m=k.Na(f+a+d+"?"+c);p.callbacks[h]=function(n){setTimeout(function(){m.parentNode&&m.parentNode.removeChild(m)},
0);e(n);try{delete p.callbacks[h]}catch(t){p.callbacks[h]=null}}}},A={vd:!1,nd:!0,A:0,Ha:5E3,Fc:12E5,interval:null,reset:function(){k.R=k.O();window.clearInterval(this.interval)},track:function(a){var d=this,c;d.interval=setInterval(function(){k.isVisible&&(d.A+=d.Ha);d.Ia()&&(d.A=0);c=g.P(a);c[b.t]=d.A;c[b.e]=d.Jb()?5E3:0;c[b.Da]=k.O();0===c[b.f]&&(c[b.f]=b.Ga);k.isVisible&&!d.Ia()&&d.Lc(c)&&0<c[b.e]&&(d.A=0,r.i(b.m,b.Ec,c));d.Nb=k.F.x;d.Ob=k.F.y;d.Mb=k.O()},d.Ha)},Jb:function(){return!0!==this.ub?
this.ub=!0:this.Nb!==k.F.x||this.Ob!==k.F.y||this.Mb!==k.O()?!0:!1},Ia:function(){return this.A>=this.Fc},Lc:function(a){return a[b.url]&&a[b.f]}},q=g.Z,B={M:[],data:{},response:null,options:null,Ad:!1,b:function(a,d){this.reset();this.options=d;this.response=a;var c=this;k.X(function(){c.height=c.xb();c.J||(c.J=function(){c.fa()});u.current[b.Tb]?c.jc():c.Oa()})},Oa:function(){typeof document.addEventListener!==b.g?document.addEventListener("scroll",this.J,!1):window.attachEvent("onscroll",this.J);
this.fa()},jc:function(){typeof document.removeEventListener!==b.g?document.removeEventListener("scroll",this.J,!1):window.detachEvent("onscroll",this.J)},fa:function(){var a=this.zb()+Math.min(document.documentElement.clientHeight,window.innerHeight||0),d=0;a>=this.height?d=q[3]:d=a/this.height*100;97<=d?this.I(q[3]):d>=q[2]?this.I(q[2]):d>=q[1]?this.I(q[1]):d>=q[0]&&this.I(q[0])},xb:function(){if(u.current[b.ja])var a=u.current[b.ja];else{a=document.body;var d=document.documentElement;a=Math.max(a.scrollHeight,
a.offsetHeight,d.clientHeight,d.scrollHeight,d.offsetHeight)}return a},zb:function(){var a="CSS1Compat"===(document.compatMode||"");return void 0!==window.pageYOffset?window.pageYOffset:a?document.documentElement.scrollTop:document.body.scrollTop},I:function(a){this.data={};if(!g.contains(q,a))l[b.error](b.wa);else if(!g.contains(this.M,a))if(this.vc(a),this.response[b.hb])this.tc();else l[b.info](b.nc)},vc:function(a){var d;for(d=0;d<q.length;d+=1){var c=q[d];a>=c&&!g.contains(this.M,c)&&(this.M.push(c),
this.data[c]=!0,l[b.info](b.Ea+c))}},H:function(){return g.ya({event:"csd",sd:this.data},this.options)},tc:function(){if(!this.response.error){var a=this.H();r.i(b.m,b.oa,a)}},reset:function(){this.M=[]}},D={za:[{name:b.cc,Qa:b.dc,Ra:b.ec,S:b.S}],kc:function(a,d){return{url:d}},Bc:function(a,d){return function(c){c={event:b.Da,url:a.url,cid:a.id,pid:a.pid,sn:a.name,data:c};g.ya(c,d);r.i(b.m,b.oa,c)}},D:function(a,d){for(var c=this.za,e,f=0;f<c.length;f+=1){e=c[f];var h=g.P(a);h.name=e.name;a[e.name]&&
r.i(e.Qa,e.Ra,this.kc(e.name,h.url),this.Bc(h,d),e.S)}}},E={track:function(a){var d=this;0===a[b.f]&&(a[b.f]=b.Ga);r.i(b.m,b.Cb,a,function(c){B.b(c,a);if(c.error)l[b.error](b.ba+c.error.code+" - "+c.error.message);else c.uid&&d.yc(c.uid),!1!==a[b.Ac]&&D.D(c,a)})},yc:function(a){x.aa(b.Ja,a,new Date(2042,5,13))}},y={md:{},U:{},ga:!1,b:function(){try{k.b();var a=window[b.gc]||window[b.oc];x.sa(b.Ca)?this.xa=!0:this.xa=!1;x.aa(b.Ca,b.$b,new Date(2042,5,13));this.D(a)}catch(d){k.X(function(){l.wc(d)})}},
D:function(a){if(a){var d;u.current=a;this.U=g.P(u.current);this.U[b.r]=this.xa;(d=this.U[b.Pa]&&this.ga)||(a[b.url]=a[b.url]||k.ma());if(a[b.url])l.b(a[b.ua]),d&&(a.hasOwnProperty(b.va)||(a[b.va]=!0),a[b.Y]=a[b.v]=a[b.referrer]=a.url),a[b.title]||(a[b.title]=k.la(a[b.url])),a[b.h]||(a[b.h]=k.ob()||g.jb(a[b.url])),a[b.L]||(d=k.ka(b.Za,b.$a))&&(a[b.L]=d),a[b.C]||(d=k.ka(b.Xa,b.Ta))&&(a[b.C]=d),a[b.B]||(d=k.mb())&&(a[b.B]=d),A.reset(),d=z.ea(a),d[b.fc]||(!1!==a[b.hc]&&(E.track(d),A.track(d)),!1!==a[b.ib]&&
this.sb(d)),this.ga=!0;else l[b.error](b.ba+b.na)}else l[b.error]("Params not passed to collect")},sb:function(a){a[b.referrer]=a[b.referrer]||k.ra();a[b.v]=z.$(a[b.v]);a[b.bb]=(new Date).getTime();a=w.encode(a);this.ia&&k.ic(this.ia);this.ia=k.Ma(b.Fa+b.eb+b.fb+"?"+a,b.x)}},v=[b.f,b.Wc,b.Pb,b.h],F={create:function(a,d){return new C(a,d)},b:function(a,d){return this.create(a,d).b()}};return{Reach:{collect:function(a){y.D(a)}},QS:{decode:w.decode},debug:l,setLogLevel:function(a){l.xc(a)},API:r,collect:function(a){y.D(a)},
decode:w.decode,init:function(){y.b()},iframeCollect:function(a){y.qd(a)},stop:function(){A.reset()},scrollDepthReached:function(a){B.I(a)},video:function(a){return F.b(a,r.T)}}}();window.SPR.init();
